# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version

fastlane_version "2.70.1"

default_platform :android

platform :android do

    before_all do
        skip_docs
    end

    desc "Deploy workflow"
    lane :beta do |options|
        supply(
            track: 'beta',
            apk: "app/build/outputs/apk/release/app-release-unsigned-signed.apk",
            skip_upload_aab: true,
            changes_not_sent_for_review: true
        )
    end
    lane :alpha do |options|
        supply(
            track: 'alpha',
            apk: "app/build/outputs/apk/release/app-release-unsigned-signed.apk",
            skip_upload_aab: true,
            changes_not_sent_for_review: true
        )
    end
    lane :playstore do |options|
        supply(
            track: 'production',
            apk: "app/build/outputs/apk/release/app-release-unsigned-signed.apk",
            skip_upload_aab: true,
            changes_not_sent_for_review: true
        )
    end
end
