about.version=1.7.0
about.build=39453
about.date=Thu Apr 02 05:47:46 2026
about.commit=362696b
about.commitFull=362696bb500f116ee3ff0da7f332226ada5dc9b5
about.github=https://github.com/glpi-project/android-inventory-agent
