about.version=1.7.1
about.build=39469
about.date=Tue Jun 02 07:50:02 2026
about.commit=1b8e5aa
about.commitFull=1b8e5aa2ae16b9a66da25ce1cab2190418ffe19f
about.github=https://github.com/glpi-project/android-inventory-agent
