about.version=1.7.0
about.build=39459
about.date=Thu Apr 02 11:29:29 2026
about.commit=a0b8f41
about.commitFull=a0b8f416aeaa4b1259c6a6673c50031b120b2bd1
about.github=https://github.com/glpi-project/android-inventory-agent
