# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.45.0"

default_platform :android

platform :android do

  desc "Alpha release app. Deploy a new version to the Google Play Store - Alpha channel"
  lane :alpha do |options|

    sign_apk(
      keystore_path: "ci/release.keystore",
      alias: "InventoryAgent",
      storepass: options[:storepass],
      tsa: "http://timestamp.comodoca.com/rfc316",
      signed_apk_path: "build/outputs/apk/",
    )

    zipalign(apk_path: "#{lane_context["build/outputs/apk/"]}")

  supply(
     track: 'alpha',
     apk: "#{lane_context["build/outputs/apk/"]}"
  )
  end
end

# how to used it fastlane android alpha storepass:'#KEYSTORE_PASSWORD' keypass:'#ALIAS_PASSWORD'
